# Generated by Django 5.1.15 on 2026-05-14 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Users who can see this event. Empty means unrestricted. Admins always see all events.', related_name='visible_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
