# Generated by Django 5.1.15 on 2026-05-14 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_event_visible_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visible_to',
        ),
        migrations.AddField(
            model_name='event',
            name='hidden_from',
            field=models.ManyToManyField(blank=True, help_text='Users blocked from seeing this event. Empty means unrestricted. Admins always see all events.', related_name='hidden_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
