# Generated by Django 5.1.15 on 2026-05-08 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0008_remove_packagetier_default_price_lead_deal_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal label shown in dropdowns (e.g. 'Info Pack — Delegate').", max_length=150, unique=True)),
                ('subject', models.CharField(help_text='Email subject line. Merge tags supported.', max_length=300)),
                ('body_html', models.TextField(help_text='Email body. Plain text or simple HTML. Merge tags supported.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal label (e.g. 'Info pack on INFO_SENT').", max_length=150)),
                ('trigger_status', models.CharField(choices=[('LEAD_ASSIGNED', 'Lead Assigned'), ('CALL_CONNECTED', 'Call Connected'), ('INFO_SENT', 'Info Sent'), ('FOLLOWUP_1', 'Follow-Up 1'), ('FOLLOWUP_2', 'Follow-Up 2'), ('FOLLOWUP_3', 'Follow-Up 3'), ('DEAL_WON', 'Deal Won'), ('DEAL_LOST', 'Deal Lost'), ('DECLINED', 'Declined')], db_index=True, help_text='The lead status that fires this rule.', max_length=24)),
                ('delay_hours', models.PositiveIntegerField(default=0, help_text='Hours after the status change before the email is sent. 0 = immediate.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(help_text='Template to use when this rule fires.', on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='emails.emailtemplate')),
            ],
            options={
                'ordering': ('trigger_status', 'delay_hours'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_rendered', models.CharField(max_length=300)),
                ('body_rendered', models.TextField()),
                ('to_email', models.EmailField(help_text='Recipient address resolved at queue time from lead.email.', max_length=254)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=FAILED.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='leads.lead')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to='emails.emailrule')),
                ('template', models.ForeignKey(help_text='Source template (kept for reference; rendered copies are stored below).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_emails', to='emails.emailtemplate')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'send_at'], name='emails_sche_status_84035f_idx'), models.Index(fields=['lead', '-created_at'], name='emails_sche_lead_id_558de2_idx')],
            },
        ),
    ]
