# Generated by Django 5.1.15 on 2026-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_register_beat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='SDR email set as Reply-To. Blank = fall back to DEFAULT_FROM_EMAIL.', max_length=254),
        ),
    ]
