# Generated by Django 5.1.15 on 2026-05-09 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_scheduledemail_from_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_email', models.EmailField(max_length=254, unique=True)),
                ('app_password', models.CharField(help_text='Zoho App Password (generated at accounts.zoho.com → Security → App Passwords).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('zoho_email',),
            },
        ),
    ]
