# Generated by Django 5.1.15 on 2026-05-09 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_useremailcredential'),
        ('leads', '0008_remove_packagetier_default_price_lead_deal_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('message_id', models.CharField(help_text='Email Message-ID header — used to deduplicate on re-poll.', max_length=500, unique=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, help_text='Matched lead. Null if no lead found with this sender email.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_emails', to='leads.lead')),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['lead', '-received_at'], name='emails_inbo_lead_id_e9b86c_idx')],
            },
        ),
    ]
