# Generated by Django 5.1.15 on 2026-04-26 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('product_interest', models.CharField(choices=[('DELEGATE_PASS', 'Delegate Pass'), ('SPONSORSHIP', 'Sponsorship'), ('SPEAKER', 'Speaker'), ('AWARD_NOMINATION', 'Award Nomination')], default='DELEGATE_PASS', max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE_FORM', 'Website Form'), ('LINKEDIN', 'LinkedIn'), ('REFERRAL', 'Referral'), ('COLD_CALL', 'Cold Call'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOWUP_SCHEDULED', 'Follow-up Scheduled'), ('INTERESTED', 'Interested'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=24)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Filled when status moves to WON / payment received.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='events.event')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('LINKEDIN', 'LinkedIn'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('NOTE', 'Note')], max_length=12)),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True, help_text='Why the status changed. Required when set via API; may be blank for admin/system changes.')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Status history',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'event_interest'], name='leads_lead_status_d70bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', '-created_at'], name='leads_lead_assigne_aefcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead', '-occurred_at'], name='leads_inter_lead_id_473ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['lead', '-changed_at'], name='leads_statu_lead_id_8e588a_idx'),
        ),
    ]
