# Generated by Django 5.1.15 on 2026-05-06 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_wipe_dummy_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='product_interest',
            field=models.CharField(choices=[('SPEAKERS', 'Speakers'), ('SPONSORS', 'Sponsors'), ('AWARDEES', 'Awardee Nomination Board'), ('VIP_MEDIA_PARTNERS', 'VIP / Media Partners & Associations'), ('DELEGATE_PASSES', 'Delegate Passes')], default='DELEGATE_PASSES', max_length=24),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead Assigned'), ('CALL_CONNECTED', 'Call Connected'), ('INFO_SENT', 'Info Sent'), ('FOLLOWUP_1', 'Follow-Up 1'), ('FOLLOWUP_2', 'Follow-Up 2'), ('FOLLOWUP_3', 'Follow-Up 3'), ('DEAL_WON', 'Deal Won'), ('DEAL_LOST', 'Deal Lost'), ('DECLINED', 'Declined')], db_index=True, default='LEAD_ASSIGNED', max_length=24),
        ),
        migrations.CreateModel(
            name='PackageTier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_interest', models.CharField(choices=[('SPEAKERS', 'Speakers'), ('SPONSORS', 'Sponsors'), ('AWARDEES', 'Awardee Nomination Board'), ('VIP_MEDIA_PARTNERS', 'VIP / Media Partners & Associations'), ('DELEGATE_PASSES', 'Delegate Passes')], db_index=True, max_length=24)),
                ('name', models.CharField(max_length=80)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested deal_value when a lead in this tier converts.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('product_interest', 'sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('product_interest', 'name'), name='uniq_tier_per_subpipeline')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='package_tier',
            field=models.ForeignKey(blank=True, help_text='Tier within the sub-pipeline (e.g. Platinum sponsor, VIP delegate). Choices filtered by product_interest.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.packagetier'),
        ),
    ]
