# Generated by Django 5.1.15 on 2026-05-08 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('leads', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPipeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-derived from the name within the event scope.', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_pipelines', to='events.event')),
            ],
            options={
                'ordering': ('event_id', 'sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('event', 'name'), name='uniq_subpipeline_per_event_name'), models.UniqueConstraint(fields=('event', 'slug'), name='uniq_subpipeline_per_event_slug')],
            },
        ),
    ]
