# Generated by Django 5.1.15 on 2026-05-08 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('leads', '0006_wipe_for_phase_2_9'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetier',
            options={'ordering': ('sub_pipeline_id', 'sort_order', 'name')},
        ),
        migrations.RemoveConstraint(
            model_name='packagetier',
            name='uniq_tier_per_subpipeline',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product_interest',
        ),
        migrations.RemoveField(
            model_name='packagetier',
            name='product_interest',
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_pipeline',
            field=models.ForeignKey(default=1, help_text='Per-event sub-pipeline (Sponsors, Speakers, etc.). Replaced the old product_interest enum in Phase 2.9.', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.subpipeline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagetier',
            name='sub_pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='leads.subpipeline'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sub_pipeline', '-created_at'], name='leads_lead_sub_pip_2ae812_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagetier',
            constraint=models.UniqueConstraint(fields=('sub_pipeline', 'name'), name='uniq_tier_per_subpipeline'),
        ),
    ]
