# Generated by Django 5.1.15 on 2026-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_packagetier_default_price_lead_deal_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead Assigned'), ('NOT_CONNECTED', 'Not Connected'), ('CALL_CONNECTED', 'Call Connected'), ('INFO_SENT', 'Info Sent'), ('PROPOSAL_SENT', 'Proposal Sent'), ('FOLLOWUP_1', 'Follow-Up 1'), ('FOLLOWUP_2', 'Follow-Up 2'), ('FOLLOWUP_3', 'Follow-Up 3'), ('INVOICE_SENT', 'Invoice Sent'), ('DEAL_WON', 'Deal Won'), ('DEAL_LOST', 'Deal Lost'), ('DECLINED', 'Declined')], db_index=True, default='LEAD_ASSIGNED', max_length=24),
        ),
    ]
