# Generated by Django 5.1.15 on 2026-05-14 06:03

from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    """Prepare Contact.email for the unique constraint:
    1. Convert '' → NULL (Postgres treats multiple NULLs as distinct).
    2. For any remaining duplicate non-null emails, keep the lowest-id row
       and null out the rest so the unique index can be created cleanly.
       (Duplicates exist in seeded data where multiple leads shared an email.)
    """
    Contact = apps.get_model("leads", "Contact")
    Contact.objects.filter(email="").update(email=None)

    # Find emails that appear more than once (excluding NULL).
    from django.db.models import Count
    dupes = (
        Contact.objects.exclude(email__isnull=True)
        .values("email")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
        .values_list("email", flat=True)
    )
    for email in dupes:
        # Keep the first (lowest id), null out the rest.
        ids = list(Contact.objects.filter(email=email).order_by("id").values_list("id", flat=True))
        Contact.objects.filter(id__in=ids[1:]).update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_not_connected_proposal_invoice_statuses'),
    ]

    operations = [
        # Step 1: Drop NOT NULL on email so the data step can write NULLs.
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, null=True, max_length=254),
        ),
        # Step 2: Convert '' → NULL and deduplicate — must happen before unique index.
        migrations.RunPython(blank_emails_to_null, migrations.RunPython.noop),
        # Step 3: Now safe to add the unique constraint.
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, null=True, unique=True, max_length=254),
        ),
        # Step 4: Phone becomes optional on Contact (drop unique index too).
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        # Step 5: Phone becomes optional on Lead.
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
