# Generated by Django 5.1.15 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_email_priority_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
